services:
  web:
    image: nginx
    expose:
      - "80"
    volumes:
      - ./front:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    image: node:18
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    command: bash -c "npm install && npm run dev"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=calculatrice
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./SQL:/docker-entrypoint-initdb.d
volumes:
  db_data:
